project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p52/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p52/
  navbar:
    logo: IQB-klein.png
    search: true
    left:
        - href: index.qmd
          text: "Metadatenprofile für Testaufgaben: Französisch Sek I"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
