project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p52/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p52/
  navbar:
    logo: iqb-logo-red.png
    search: true
    left:
      - href: index.qmd
        text: "Metadatenprofile für Testaufgaben: Französisch Sek I"
    right:
      - icon: github
        href: https://github.com/iqb-vocabs/p52
        aria-label: Source Code


lang: de

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
